name: Generate Release
on: push
jobs:
  linux-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Compile
        run: make

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: linux
          path: icegen
          retention-days: 1

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v2
  windows-release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Get Dependencies
        run: go get ./...

      - name: Compile
        run: go build ./...

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: windows
          path: icegen
          retention-days: 1

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v2

  macos-release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Get Dependencies
        run: go get ./...

      - name: Compile
        run: go build ./...

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: macos
          path: icegen
          retention-days: 1

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v2
