name: Generate Release
on:
  workflow_dispatch:
    branches:
      - master
      - v0.1.0-beta
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.3
      - name: Compile
        run: make
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: icegen
          path: icegen.zip
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v2