name: Generate Release
on:
  workflow_dispatch:
    branches:
      - master
      - v0.1.0
    inputs:
      branch:
        description: Branch to build
        required: true
jobs:
  linux-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Compile
        run: make

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: icegen-linux
          path: |
            icegen
            templates
          retention-days: 1

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v2
  windows-release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Get Dependencies
        run: go get

      - name: Compile
        run: go build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: icegen-windows
          path: |
            icegen.exe
            templates
          retention-days: 1

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v2

  macos-release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Compile
        run: make

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: icegen-macos
          path: |
            icegen
            templates
          retention-days: 1

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v2
